### ISSUE TITLE
Finish Vision documentation

### ISSUE THREAD

**Issue by carrogross** [kth-ii1302-vt22-group-3/README#30]

**Comment by carrogross** [comment]
https://docs.google.com/document/d/1OBW36KN6-4BQBYUhIrJsCLajsyaiZiV4/edit

**Comment by carrogross** [comment]
Har lagt in ändringsförslag och någon enstaka kommentar i Visionsdokumentet nu. Ser överlag asbra ut, riktigt snyggt med tabellen från MoSCoW!!

**Comment by natashadonner** [comment]
Har godkänt ändringförslag och lagt till några meningar innan varje tabell.
