### ISSUE TITLE
Slides (powerpoint)

### ISSUE THREAD

**Issue by natashadonner** [kth-ii1302-vt22-group-3/README#31]

**Comment by natashadonner** [comment]
- Created all slides
- Added MoSCoW 
- Added funny intro text to product overview
Link to PP https://docs.google.com/presentation/d/15B1LOn16VhLBNEwLkiIXITlcD0RfojP0lPZSYAzaqKs/edit

**Comment by arifjehoh** [comment]
I have updated the slides with Scrum Board and Sprint 2, Web and Database & API images and text.
